### ISSUE TITLE
MQTT

### ISSUE THREAD

**Issue by fracz** [SUPLA/supla-cloud#404]
Do tego będę potrzebował dodatkową zakładkę w Integracjach. Jeśli w parameters.yml będzie włączona opcja “mqtt_broker” to w integracjach pojawi się zakładka “MQTT” lub “MQTT Broker” (nie mogę się zdecydować). Tam Checkbox “Udostępnij swoje urządzenia za pośrednictwem MQTT brokera”. Po zaznaczeniu tej opcji powinny się pojawić dane mqtt_brokera z parameters.yml, czyli adres, port, protokół. Dodatkowo jeśli w config_local.yml będzie włączona opcja supla_mqtt_broker_auth_plugin (domyślnie wyłączone) to pod adresem serwera powinny się pojawić dane logowania do mqttbrokera czyli adres email konta (username) oraz dedykowane hasło wraz z możliwością zmiany tego hasła.  W mysql.supla_user powinny dojść dwa pola mqtt_broker_enabled (bool) oraz mqtt_broker_auth_password szyfrowane bcrypt-em (siła taka jak przy auth_key).  Docelowo chciałbym udostępnić generator konfiguracji dla home assistanta, który jednym kliknięciem wygeneruje config dla wybranego kanału, który wystarczy tylko wkleić do HA.

**Comment by fracz** [comment]
Config:

```yml
supla:
    mqtt_broker:

        # Should the MQTT Broker be enabled?
        enabled:              true

        # MQTT Broker address (host)
        host:                 ~

        # MQTT Broker protocol
        protocol:             ~

        # MQTT Broker port
        port:                 ~

        # Does MQTT Broker require authorization?
        auth:                 false
```

**Comment by przemyslawzygmunt** [comment]
"Should MQTT settings be available?"

**Comment by przemyslawzygmunt** [comment]
# Encrypted connection (tls)
tls: ~

**Comment by przemyslawzygmunt** [comment]
auth -> integrated_auth 

*supla_mqtt_broker_auth_plugin

**Comment by fracz** [comment]
```yml
supla:
    mqtt_broker:
        # Should MQTT settings be available?
        enabled:              false
        # MQTT Broker address (host)
        host:                 ~
        # MQTT Broker protocol
        protocol:             ~
        # MQTT Broker port
        port:                 ~
        # Is TLS enabled?
        tls:                  false
        # Does MQTT Broker require authorization?
        integrated_auth:      false
```
