### ISSUE TITLE
HomeAssistant config in MQTT Setting Page

### ISSUE THREAD

**Issue by fracz** [SUPLA/supla-cloud#411]
```yml
mqtt:
  broker: HOST
  port: 8883
  certificate: auto
  username: USER
  password: *****
```
