### ISSUE TITLE
Another database for logs

### ISSUE THREAD

**Issue by fracz** [SUPLA/supla-cloud#656]

**Comment by fracz** [comment]
If an instance needs to store logs in another database, do the following:

1. Copy the database to the new location. You need to copy the FULL SCHEMA (because migrations will likely complain for missing tables). You may copy all of the data, too, but it is not required. You may only copy the data for all of the `supla_*_logs` tables and the `migration_versions` table.
2. Configure application to use the new location for fetching logs in `app/config/config_local.yml`

```yml
doctrine:
  dbal:
    connections:
      measurement_logs:
        dbname: "supla_logs"
        host: "supla_logs_host"
        user: "username"
        password: "password"
        port: "3306"
```

3. Remember to run migrations in the new database on every update. You may also run them now (they should report no migrations to execute if you copied the database correctly).
    ```
    php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration --em measurement_logs
    ```

The list of the tables that will be used from the new connection:

* `supla_em_log`
* `supla_em_voltage_log`
* `supla_ic_log`
* `supla_temperature_log`
* `supla_temphumidity_log`
* `supla_thermostat_log`
