### ISSUE TITLE
Add pairing status display in UI

### ISSUE THREAD

**Issue by przemyslawzygmunt** [SUPLA/supla-cloud#836]

**Comment by fracz** [comment]
![image](https://github.com/user-attachments/assets/136e7236-9065-48a7-aaa9-ac4edd6257ad)
![image](https://github.com/user-attachments/assets/56df745c-73c5-4e55-82da-4e8561642667)
![image](https://github.com/user-attachments/assets/840a1ec4-9500-411d-9b19-5ed2cfce7a60)

**Comment by fracz** [comment]
```yml
subdevicePairingResult_NOT_SUPPORTED: Pairing not supported on the device.
subdevicePairingResult_UNAUTHORIZED: Pairing unauthorized.
subdevicePairingResult_ONGOING: Pairing in progress.
subdevicePairingResult_CMD_RESULT_UNKNOWN: Unknown command result ({resultNum}).
subdevicePairingResult_PROCEDURE_STARTED: Pairing procedure started.
subdevicePairingResult_NO_NEW_DEVICE_FOUND: No new device found.
subdevicePairingResult_SUCCESS: Pairing successful.
subdevicePairingResult_RESOURCES_LIMIT_EXCEEDED: Pairing resources limit exceeded.
subdevicePairingResult_NOT_STARTED_BUSY: Pairing not started because the device is busy.
subdevicePairingResult_PAIRING_RESULT_UNKNOWN: Unknown pairing result ({resultNum}).
```
